### ISSUE TITLE
bug: fail to deploy Gateway on Flow

### ISSUE THREAD

**Issue by Tanguyabel** [jina-ai/now#1094]
For some time now, and after no obvious changes on our code, the deployment of a remote flow fails while deploying the gateway:

```
Traceback (most recent call last):
  File "/usr/local/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/usr/local/lib/python3.8/site-packages/jina_cli/api.py", line 116, in gateway
    with runtime_cls(args) as runtime:
  File "/usr/local/lib/python3.8/site-packages/jina/serve/runtimes/gateway/__init__.py", line 48, in __init__
    super().__init__(args, cancel_event, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jina/serve/runtimes/asyncio.py", line 78, in __init__
    self._loop.run_until_complete(self.async_setup())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/jina/serve/runtimes/gateway/__init__.py", line 63, in async_setup
    self.gateway = BaseGateway.load_config(
  File "/usr/local/lib/python3.8/site-packages/jina/jaml/__init__.py", line 792, in load_config
    obj = JAML.load(tag_yml, substitute=False, runtime_args=runtime_args)
  File "/usr/local/lib/python3.8/site-packages/jina/jaml/__init__.py", line 174, in load
    r = yaml.load(stream, Loader=get_jina_loader_with_runtime(runtime_args))
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.8/site-packages/jina/jaml/__init__.py", line 582, in _from_yaml
    return get_parser(cls, version=data.get('version', None)).parse(
  File "/usr/local/lib/python3.8/site-packages/jina/jaml/parsers/gateway/legacy.py", line 56, in parse
    obj = cls(
  File "/usr/local/lib/python3.8/site-packages/jina/serve/helper.py", line 73, in arg_wrapper
    f = func(self, *args, **kwargs)
  File "/workdir/now_gateway.py", line 112, in __init__
    self._add_gateway(
TypeError: _add_gateway() got multiple values for argument 'port'
```

**Comment by Tanguyabel** [comment]
For some reason the way `NOWGateway` get instantiated may have changed as it now receives arguments set in the flow, in particular `port` and `protocol`. When the complete set of arguments is forwarded as is to the function `_add_gateway`, it ends with a clash in names for those arguments. The fix for now is to pop them from the arguments we forward.
