### ISSUE TITLE
Using BFF to query for images fails

### ISSUE THREAD

**Issue by joschkabraun** [jina-ai/now#183]
Searching with an image through the BFF causes an `PIL.UnidentifiedImageError: cannot identify image file` error in local deployment of `best-artworks` dataset with `medium` quality.

Traceback:
```
encoder_clip@ 1[E]:UnidentifiedImageError('cannot identify image file <_io.BytesIO object at 0x7fd7af683650>')
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jina/serve/runtimes/worker/__init__.py", line 136, in process_data
    return await self._data_request_handler.handle(requests=requests)
  File "/usr/local/lib/python3.7/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 137, in handle
    field='docs',
  File "/usr/local/lib/python3.7/site-packages/jina/serve/executors/__init__.py", line 250, in __acall__
    return await self.__acall_endpoint__(__default_endpoint__, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jina/serve/executors/__init__.py", line 265, in __acall_endpoint__
    return func(self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jina/serve/executors/decorators.py", line 127, in arg_wrapper
    return fn(executor_instance, *args, **kwargs)
  File "/workspace/executor.py", line 132, in encode
    self._encode_images(batch)
  File "/workspace/executor.py", line 140, in _encode_images
    d_tmp.convert_blob_to_image_tensor()
  File "/usr/local/lib/python3.7/site-packages/docarray/document/mixins/image.py", line 47, in convert_blob_to_image_tensor
    tensor = _to_image_tensor(io.BytesIO(self.blob), width=width, height=height)
  File "/usr/local/lib/python3.7/site-packages/docarray/document/mixins/image.py", line 333, in _to_image_tensor
    raw_img = Image.open(source)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 3009, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fd7af683650>
```

Steps to reproduce bug:

1. Execute `jina-now start` from `origin/main`
2. Configure `best-artworks`, `medium` quality and `local` deployment
3. After finish of CLI execute:

```
from jina import Client
from deployment.frontend.frontend import load_data
import  base64


host = 'localhost'
port = '31080'

c = Client(host=host, port=port)

da_img = load_data('https://storage.googleapis.com/jina-fashion-data/data/one-line/datasets/jpeg/best-artworks.img10.bin')

# using the first example of best-artworks
query_doc = da_img[0]
docs = c.post('/search', query_doc, parameters={'limit': 9})
print(f"Number of results for entire doc: {len(docs[0].matches)}")


# using only blob as input
query_doc = Document(blob=da_img[0].blob)
docs = c.post('/search', query_doc, parameters={'limit': 9})
print(f"Number of results for only blob attribute: {len(docs[0].matches)}")


# transform as in frontend.search_by_file
if query_doc.blob != b'':
    query_doc.convert_blob_to_image_tensor()
query_doc.set_image_tensor_shape((224, 224))
# need decode('utf-8') to send via requests.post()
image = base64.b64encode(query_doc.tensor).decode('utf-8')

# transform as in bff.api.v1.routers.helper
base64_bytes = image.encode('utf-8')
message_bytes = base64.decodebytes(base64_bytes)
query_doc = Document(blob=message_bytes)

docs = c.post('/search', query_doc, parameters={'limit': 9})
print(f"Only blob as in BFF and frontend transformations: {len(docs[0].matches)}")
```

**Comment by joschkabraun** [comment]
Fixed it by doing:
```
from jina import Client
from deployment.frontend.frontend import load_data
import  base64


host = 'localhost'
port = '31080'

c = Client(host=host, port=port)

da_img = load_data('https://storage.googleapis.com/jina-fashion-data/data/one-line/datasets/jpeg/best-artworks.img10.bin')

# using the first example of best-artworks
query_doc = da_img[0]
docs = c.post('/search', query_doc, parameters={'limit': 9})
print(f"Number of results for entire doc: {len(docs[0].matches)}")


# using only blob as input
query_doc = Document(blob=da_img[0].blob)
docs = c.post('/search', query_doc, parameters={'limit': 9})
print(f"Number of results for only blob attribute: {len(docs[0].matches)}")


image = base64.b64encode(query_doc.blob).decode('utf-8')

# transform as in bff.api.v1.routers.helper
base64_bytes = image.encode('utf-8')
message_bytes = base64.decodebytes(base64_bytes)
query_doc = Document(blob=message_bytes)

docs = c.post('/search', query_doc, parameters={'limit': 9})
print(f"Only blob as in BFF and frontend transformations: {len(docs[0].matches)}")
```
