### ISSUE TITLE
No such file or directory: 'requirements-test.txt'

### ISSUE THREAD

**Issue by jjairitech** [jina-ai/now#234]
Hello, 
I tried create either docker container or Anaconda environment on both Windows and WSL2 
then run "pip install jina-now"

No hope, I got these kind of error.

=========================================
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpa791kcil get_requires_for_build_wheel /tmp/tmpqxbv4wwf
       cwd: /tmp/pip-install-v1scfop0/jina-now
  Complete output (24 lines):
  Traceback (most recent call last):
    File "/tmp/tmpa791kcil", line 280, in <module>
      main()
    File "/tmp/tmpa791kcil", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpa791kcil", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-zk659jh7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-zk659jh7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-zk659jh7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-zk659jh7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 42, in <module>
      extra_require = get_requirements_list('requirements-test.txt')
    File "setup.py", line 11, in get_requirements_list
      with pathlib.Path(f).open() as requirements_txt:
    File "/usr/lib/python3.8/pathlib.py", line 1222, in open
      return io.open(self, mode, buffering, encoding, errors, newline,
    File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
      return self._accessor.open(self, flags, mode)
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements-test.txt'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpa791kcil get_requires_for_build_wheel /tmp/tmpqxbv4wwf Check the logs for full command output.
=========================================

What I tried are as below, row by row.

conda create -n jina-now-test python=3.8
conda activate jina-now-test
git clone https://github.com/jina-ai/now.git
cd now
pip install -r requirements.txt
pip install jina-now

**Comment by slettner** [comment]
Hi @jjairitech,

thank you for submitting this issue. I think this problem has been solved in the last release and the file exists now.

To install JinaNOW execute `pip install -U jina-now`

Cloning the repo should only be required in case you intent to make changes to the code base.
Let me know if this works for you.

**Comment by jjairitech** [comment]
Dear @slettner 
Thanks for letting me know.
I could not try that at the moment, but I think it is ok to close this issue.

**Comment by makram93** [comment]
Closing this issue as it is addressed already.

@jjairitech Thank you for trying out Jina NOW and raising this issue. We look forward to your valuable feedback!
