### ISSUE TITLE
jina now start breaks after jina auth logout

### ISSUE THREAD

**Issue by fogx** [jina-ai/now#475]
After logging out of jina auth, it is not possible to run `jina now start` anymore until i reauthenticate. This should not be a requirement to run the CLI locally.
```Traceback (most recent call last):
  File "/home/jina/.local/bin/jina-now", line 8, in <module>
    sys.exit(cli())
  File "/home/jina/.local/lib/python3.10/site-packages/now/cli/__init__.py", line 119, in cli
    args = _get_run_args()
  File "/home/jina/.local/lib/python3.10/site-packages/now/cli/__init__.py", line 26, in _get_run_args
    parser = get_main_parser()
  File "/home/jina/.local/lib/python3.10/site-packages/now/cli/parser.py", line 153, in get_main_parser
    set_start_parser(sp)
  File "/home/jina/.local/lib/python3.10/site-packages/now/cli/parser.py", line 109, in set_start_parser
    set_default_start_args(parser)
  File "/home/jina/.local/lib/python3.10/site-packages/now/cli/parser.py", line 63, in set_default_start_args
    choices=[app for app in Apps() if _construct_app(app).is_enabled],
  File "/home/jina/.local/lib/python3.10/site-packages/now/cli/parser.py", line 63, in <listcomp>
    choices=[app for app in Apps() if _construct_app(app).is_enabled],
  File "/home/jina/.local/lib/python3.10/site-packages/now/dialog.py", line 44, in _construct_app
    return getattr(
  File "/home/jina/.local/lib/python3.10/site-packages/now/apps/text_to_video/app.py", line 35, in __init__
    super().__init__()
  File "/home/jina/.local/lib/python3.10/site-packages/now/apps/base/app.py", line 25, in __init__
    self.set_flow_yaml()
  File "/home/jina/.local/lib/python3.10/site-packages/now/apps/text_to_video/app.py", line 68, in set_flow_yaml
    is_jina_email = _get_email().split('@')[-1] == 'jina.ai'
  File "/home/jina/.local/lib/python3.10/site-packages/now_common/utils.py", line 206, in _get_email
    user_token = config_val['auth_token']
KeyError: 'auth_token'
```

**Comment by florian-hoenicke** [comment]
fixed by @makram93
