### ISSUE TITLE
Music-to-music: Crash on Flow deploy

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/now#531]
Choosing music to music search leads to failed Flow deployment:

```
Unexpected status: FAILED reached at STARTING for Flow ID 7eaf10f5db with request_id 7cea37f9-5b56-4142-a5c4-0024dfaa632e
```

`jc list` shows no running Flows

## Recreate the bug

```
? What sort of search engine would you like to build?  🥁 ▶ 🥁 music to music search
? What dataset do you want to use?  🎸 rock music (≈2K songs)
? Where do you want to deploy your search engine?  ⛅️ Jina Cloud
? Do you want to secure the flow?  ⛔ no
```

## Full terminal output

```
? What sort of search engine would you like to build?  🥁 ▶ 🥁 music to music search
? What dataset do you want to use?  🎸 rock music (≈2K songs)
? Where do you want to deploy your search engine?  ⛅️ Jina Cloud
? Do you want to secure the flow?  ⛔ no
⬇  Download DocArray dataset
📂 Extracting dataset from DocArray
⚡️ Using cached hub model for speed
Unexpected status: FAILED reached at STARTING for Flow ID 7eaf10f5db with request_id 7cea37f9-5b56-4142-a5c4-0024dfaa632e
```

**Comment by deepankarm** [comment]
### JCloud logs for `7eaf10f5db`

```
------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                                         message                                                                          |
|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| INFO     - 🌨️ JCloud - Connecting to the database..                                                                                                     |
| INFO     - 🌨️ JCloud - Successfully connected to the database                                                                                           |
| INFO     - 🌨️ JCloud [7eaf10f5db] - Starting deloyment for flow: 7eaf10f5db ...                                                                         |
| INFO     - 🌨️ JCloud [7eaf10f5db] - Creating Flow from                                                                                                  |
|          jtype: Flow                                                                                                                                     |
|          with:                                                                                                                                           |
|            name: nowapi                                                                                                                                  |
|            monitoring: true                                                                                                                              |
|            port_expose: 8080                                                                                                                             |
|            prefetch: 10                                                                                                                                  |
|            cors: True                                                                                                                                    |
|            env:                                                                                                                                          |
|              JINA_LOG_LEVEL: DEBUG                                                                                                                       |
|          jcloud:                                                                                                                                         |
|            version: ${{ ENV.JINA_VERSION }}                                                                                                              |
|            retention_days: ${{ RETENTION_DAYS }}                                                                                                         |
|          executors:                                                                                                                                      |
|            - name: preprocessor                                                                                                                          |
|              uses: ${{ ENV.PREPROCESSOR_NAME }}                                                                                                          |
|              uses_with:                                                                                                                                  |
|                app: ${{ ENV.APP }}                                                                                                                       |
|                admin_emails: ${{ ENV.ADMIN_EMAILS }}                                                                                                     |
|                user_emails: ${{ ENV.USER_EMAILS }}                                                                                                       |
|              jcloud:                                                                                                                                     |
|                resources:                                                                                                                                |
|                  memory: 1G                                                                                                                              |
|              env:                                                                                                                                        |
|                JINA_LOG_LEVEL: DEBUG                                                                                                                     |
|            - name: encoder_music                                                                                                                         |
|              uses: ${{ ENV.ENCODER_NAME }}                                                                                                               |
|              jcloud:                                                                                                                                     |
|                resources:                                                                                                                                |
|                  memory: 4G                                                                                                                              |
|              env:                                                                                                                                        |
|                JINA_LOG_LEVEL: DEBUG                                                                                                                     |
|            - name: linear_head                                                                                                                           |
|              uses: ${{ ENV.LINEAR_HEAD_NAME }}                                                                                                           |
|              uses_with:                                                                                                                                  |
|                finetune_layer_size: ${{ ENV.FINETUNE_LAYER_SIZE }}                                                                                       |
|                pre_trained_embedding_size: ${{ ENV.PRE_TRAINED_EMBEDDINGS_SIZE }}                                                                        |
|              env:                                                                                                                                        |
|                JINA_LOG_LEVEL: DEBUG                                                                                                                     |
|            - name: postprocessor                                                                                                                         |
|              uses: jinahub+docker://NOWPostprocessor/v0.0.5                                                                                              |
|              env:                                                                                                                                        |
|                JINA_LOG_LEVEL: DEBUG                                                                                                                     |
|            - name: indexer                                                                                                                               |
|              uses: ${{ ENV.INDEXER_NAME }}                                                                                                               |
|              uses_with:                                                                                                                                  |
|                dim: ${{ ENV.N_DIM }}                                                                                                                     |
|                columns: ${{ ENV.COLUMNS }}                                                                                                               |
|                admin_emails: ${{ ENV.ADMIN_EMAILS }}                                                                                                     |
|                user_emails: ${{ ENV.USER_EMAILS }}                                                                                                       |
|              jcloud:                                                                                                                                     |
|                capacity: on-demand                                                                                                                       |
|                resources:                                                                                                                                |
|                  memory: ${{ ENV.INDEXER_MEM }}                                                                                                          |
|                  cpu: 1.0                                                                                                                                |
|              env:                                                                                                                                        |
|                JINA_LOG_LEVEL: DEBUG                                                                                                                     |
| DEBUG    - 🌨️ JCloud [7eaf10f5db] - Creating namespace 'jnamespace-7eaf10f5db' with annotations: {'jina.ai/jina-version': '3.9.1',                      |
|          'jina.ai/retention-days': '7', 'jina.ai/user': '627138dd41855bd0e597f32e', 'jina.ai/email': 'alexcg@outlook.com', 'jina.ai/user-tier':          |
|          'free', 'jina.ai/gpu-enabled': '0'}                                                                                                             |
| INFO     - 🌨️ JCloud [7eaf10f5db] - Updating workspace to jworkspace-7eaf10f5db for all non-sandbox Executors ...                                       |
| DEBUG    - 🌨️ JCloud [7eaf10f5db] - Starting the generation of k8s yaml...                                                                              |
| DEBUG    - 🌨️ JCloud [7eaf10f5db] - Deploying Flow with jina version: 3.9.1, protocol: GRPC                                                             |
| Traceback (most recent call last):                                                                                                                       |
|   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                             |
|     return _run_code(code, main_globals, None,                                                                                                           |
|   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code                                                                                        |
|     exec(code, run_globals)                                                                                                                              |
|   File "/wolf/k8s/deployments/to_k8s_yaml.py", line 97, in <module>                                                                                      |
|     to_k8s_yaml()                                                                                                                                        |
|   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in                                                                             |
| __call__                                                                                                                                                 |
|     return self.main(*args, **kwargs)                                                                                                                    |
|   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in                                                                             |
| main                                                                                                                                                     |
|     rv = self.invoke(ctx)                                                                                                                                |
|   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in                                                                             |
| invoke                                                                                                                                                   |
|     return ctx.invoke(self.callback, **ctx.params)                                                                                                       |
|   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in                                                                              |
| invoke                                                                                                                                                   |
|     return __callback(*args, **kwargs)                                                                                                                   |
|   File "/wolf/k8s/deployments/to_k8s_yaml.py", line 89, in to_k8s_yaml                                                                                   |
|     f.to_k8s_yaml(                                                                                                                                       |
|   File "/usr/local/lib/python3.8/site-packages/jina/orchestrate/flow/base.py",                                                                           |
| line 2292, in to_kubernetes_yaml                                                                                                                         |
|     configs = k8s_deployment.to_kubernetes_yaml()                                                                                                        |
|   File                                                                                                                                                   |
| "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/k8s.                                                                         |
| py", line 353, in to_kubernetes_yaml                                                                                                                     |
|     return [                                                                                                                                             |
|   File                                                                                                                                                   |
| "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/k8s.                                                                         |
| py", line 356, in <listcomp>                                                                                                                             |
|     deployment.get_runtime_yamls(),                                                                                                                      |
|   File                                                                                                                                                   |
| "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/k8s.                                                                         |
| py", line 124, in get_runtime_yamls                                                                                                                      |
|     image_name = self._get_image_name(cargs.uses)                                                                                                        |
|   File                                                                                                                                                   |
| "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/k8s.                                                                         |
| py", line 106, in _get_image_name                                                                                                                        |
|     image_name = get_image_name(uses)                                                                                                                    |
|   File                                                                                                                                                   |
| "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/help                                                                         |
| er.py", line 25, in get_image_name                                                                                                                       |
|     meta_data, _ = HubIO.fetch_meta(                                                                                                                     |
|   File "/usr/local/lib/python3.8/site-packages/jina/hubble/helper.py", line 378,                                                                         |
| in wrapper                                                                                                                                               |
|     result = func(*args, **kwargs)                                                                                                                       |
|   File "/usr/local/lib/python3.8/site-packages/jina/hubble/hubio.py", line 716,                                                                          |
| in fetch_meta                                                                                                                                            |
|     resp = _send_request_with_retry(pull_url, json=payload, headers=req_header)                                                                          |
|   File "/usr/local/lib/python3.8/site-packages/jina/helper.py", line 185, in                                                                             |
| wrapper                                                                                                                                                  |
|     return func(*args, **kwargs)                                                                                                                         |
|   File "/usr/local/lib/python3.8/site-packages/jina/hubble/hubio.py", line 699,                                                                          |
| in _send_request_with_retry                                                                                                                              |
|     raise Exception(resp.text)                                                                                                                           |
| Exception: {"code":500,"status":50000,"message":"Error: At #input(manifesturl):                                                                          |
| Validator 'gitUrlMaxLength2048' has thrown an error: Error: URL parsing                                                                                  |
| failed.."}                                                                                                                                               |
| INFO     - 🌨️ JCloud [7eaf10f5db] - Cleaning up endpoints ...                                                                                           |
| CRITICAL - 🌨️ JCloud [7eaf10f5db] - Deployment failed for Flow 'jflow-7eaf10f5db': 'Traceback (most recent call last):                                  |
|            File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                    |
|              return _run_code(code, main_globals, None,                                                                                                  |
|            File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code                                                                               |
|              exec(code, run_globals)                                                                                                                     |
|            File "/wolf/k8s/deployments/to_k8s_yaml.py", line 97, in <module>                                                                             |
|              to_k8s_yaml()                                                                                                                               |
|            File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__                                                           |
|              return self.main(*args, **kwargs)                                                                                                           |
|            File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main                                                               |
|              rv = self.invoke(ctx)                                                                                                                       |
|            File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke                                                             |
|              return ctx.invoke(self.callback, **ctx.params)                                                                                              |
|            File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke                                                              |
|              return __callback(*args, **kwargs)                                                                                                          |
|            File "/wolf/k8s/deployments/to_k8s_yaml.py", line 89, in to_k8s_yaml                                                                          |
|              f.to_k8s_yaml(                                                                                                                              |
|            File "/usr/local/lib/python3.8/site-packages/jina/orchestrate/flow/base.py", line 2292, in to_kubernetes_yaml                                 |
|              configs = k8s_deployment.to_kubernetes_yaml()                                                                                               |
|            File "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/k8s.py", line 353, in to_kubernetes_yaml                     |
|              return [                                                                                                                                    |
|            File "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/k8s.py", line 356, in <listcomp>                             |
|              deployment.get_runtime_yamls(),                                                                                                             |
|            File "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/k8s.py", line 124, in get_runtime_yamls                      |
|              image_name = self._get_image_name(cargs.uses)                                                                                               |
|            File "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/k8s.py", line 106, in _get_image_name                        |
|              image_name = get_image_name(uses)                                                                                                           |
|            File "/usr/local/lib/python3.8/site-packages/jina/orchestrate/deployments/config/helper.py", line 25, in get_image_name                       |
|              meta_data, _ = HubIO.fetch_meta(                                                                                                            |
|            File "/usr/local/lib/python3.8/site-packages/jina/hubble/helper.py", line 378, in wrapper                                                     |
|              result = func(*args, **kwargs)                                                                                                              |
|            File "/usr/local/lib/python3.8/site-packages/jina/hubble/hubio.py", line 716, in fetch_meta                                                   |
|              resp = _send_request_with_retry(pull_url, json=payload, headers=req_header)                                                                 |
|            File "/usr/local/lib/python3.8/site-packages/jina/helper.py", line 185, in wrapper                                                            |
|              return func(*args, **kwargs)                                                                                                                |
|            File "/usr/local/lib/python3.8/site-packages/jina/hubble/hubio.py", line 699, in _send_request_with_retry                                     |
|              raise Exception(resp.text)                                                                                                                  |
|          Exception: {"code":500,"status":50000,"message":"Error: At #input(manifesturl): Validator 'gitUrlMaxLength2048' has thrown an error: Error:     |
|          URL parsing failed.."}                                                                                                                          |
|          '                                                                                                                                               |
| DEBUG    - 🌨️ JCloud [7eaf10f5db] - Deleting the Flow jflow-7eaf10f5db ...                                                                              |
| DEBUG    - 🌨️ JCloud [7eaf10f5db] - Ingress `wolf` doesn't exist in namespace `jnamespace-7eaf10f5db`. Nothing to delete!                               |
| INFO     - 🌨️ JCloud [7eaf10f5db] - Deleting namespace `jnamespace-7eaf10f5db` ...                                                                      |
| DEBUG    - 🌨️ JCloud [7eaf10f5db] - waiting for Flow jnamespace-7eaf10f5db to be deleted.. sleeping for 10secs                                          |
| INFO     - 🌨️ JCloud [7eaf10f5db] - Flow deleted successfully!                                                                                          |
| INFO     - 🌨️ JCloud [7eaf10f5db] - Workspace `jworkspace-7eaf10f5db` doesn't exist. Nothing to delete!                                                 |
------------------------------------------------------------------------------------------------------------------------------------------------------------
```
