### ISSUE TITLE
bug: initialize package too often

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#539]
I was running the text-to-text+image app. The following issues occurred:
- [x] multiple initializations of our package
![Image](https://user-images.githubusercontent.com/11627845/192268192-46c93e8b-a301-4838-8028-ff984703bcf3.png)
- [ ] if finetuner API is down, it should be skipped instead of aborting the process.  The user should just be informed that fine-tuning is skipped.
```
🔧 Perform finetuning!
💪 fine-tuning:
Traceback (most recent call last):
  File "/Users/florianhonicke/jina/now/now/cli/__init__.py", line 147, in <module>
    cli()
  File "/Users/florianhonicke/jina/now/now/cli/__init__.py", line 143, in cli
    return run_k8s(os_type=os_type, arch=arch, **args)
  File "/Users/florianhonicke/jina/now/now/run_all_k8s.py", line 168, in run_k8s
    **kwargs,
  File "/Users/florianhonicke/jina/now/now/run_all_k8s.py", line 111, in start_now
    ) = run_backend.run(app_instance, user_input, kubectl_path=kwargs['kubectl_path'])
  File "/Users/florianhonicke/jina/now/now/log/log.py", line 58, in profiled_fun
    result = fun(*args, **kwargs)
  File "/Users/florianhonicke/jina/now/now/run_backend.py", line 33, in run
    dataset=dataset, user_input=user_input, kubectl_path=kubectl_path
  File "/Users/florianhonicke/jina/now/now/apps/text_to_text_and_image/app.py", line 125, in setup
    kubectl_path=kubectl_path,
  File "/Users/florianhonicke/jina/now/now/log/log.py", line 58, in profiled_fun
    result = fun(*args, **kwargs)
  File "/Users/florianhonicke/jina/now/now/finetuning/run_finetuning.py", line 78, in finetune
    return _finetune_model(finetune_ds, finetune_settings)
  File "/Users/florianhonicke/jina/now/now/log/log.py", line 58, in profiled_fun
    result = fun(*args, **kwargs)
  File "/Users/florianhonicke/jina/now/now/finetuning/run_finetuning.py", line 109, in _finetune_model
    finetuner.login()
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/finetuner/__init__.py", line 32, in login
    ft.login()
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/finetuner/finetuner.py", line 29, in login
    self._default_experiment = self._get_default_experiment()
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/finetuner/finetuner.py", line 40, in _get_default_experiment
    for experiment in self.list_experiments():
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/finetuner/finetuner.py", line 80, in list_experiments
    experiment_infos = self._client.list_experiments()
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/finetuner/client/client.py", line 57, in list_experiments
    return self._handle_request(url=url, method=GET)
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/finetuner/client/base.py", line 88, in _handle_request
    details=response.json()['detail'],
finetuner.exception.FinetunerServerError: Internal Server Error (500): Unknown error on the server-side

```

**Comment by jupyterjazz** [comment]
Regarding the second point, currently text to text+image app is implemented in a way that fine-tuning is **required**. Changing this is not simple because:
- we can't get clip and sbert models without finetuner
- we don't know how well it works

I think this should be addressed after we have a first working version
